# Pytorch基础使用

**调用torch库**

In [2]:
import torch
torch.__version__

'2.5.1'

**张量的创建与变形**

In [3]:
# 直接构建
# 0-d, 1-d, 2-d ......
v1 = torch.tensor(10)
v2 = torch.tensor([1, 2, 3, 4])
v3 = torch.tensor([[1, 2, 3], [3, 4, 5]])

In [22]:
# API方法构造
m1 = torch.rand(5, 3)  # [0, 1]均匀分布
m2 = torch.randn(1, 3, 4)  # mean:0, std:1
m3 = torch.zeros(5, 3)
m4 = torch.ones(4, 1)
m5 = torch.linspace(1, 10, 3)

In [23]:
# 尺寸
print(m2.size())
print(m3.shape)

torch.Size([1, 3, 4])
torch.Size([5, 3])


In [26]:
# reshape
m6 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m7 = m6.reshape(2, 5)

**张量索引**

In [27]:
# 张量索引 [start, end)
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x[3])  # 4
print(x[3:5])  # [4, 5]
print(x[:5])
print(x[3:-2])
print(x[:-1])

tensor(4)
tensor([4, 5])
tensor([1, 2, 3, 4, 5])
tensor([4, 5, 6, 7, 8])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


整体操作和 numpy 差不多，其实这些框架的基本操作基本都是大同小异

**与 numpy，pandas 结合**

In [29]:
import numpy as np
import pandas as pd

v4 = np.array([2, 3, 4, 5])
v5 = torch.tensor(v4)
v6_dataframe = pd.DataFrame([1, 2, 3])
v7 = torch.tensor(v6_dataframe.values)

**数据类型转换**

In [35]:
x1 = torch.tensor(10)  # 0-d 
x2 = torch.tensor([0.85, 0.12, 0.34])  # n-d tensor
print(type(x1), type(x1.item()), x1.item())
print(type(x2), type(x2.tolist()), x2.tolist())
print(type(x1.numpy()), x1.numpy())
print(type(x2.numpy()), x2.numpy())

<class 'torch.Tensor'> <class 'int'> 10
<class 'torch.Tensor'> <class 'list'> [0.8500000238418579, 0.11999999731779099, 0.3400000035762787]
<class 'numpy.ndarray'> 10
<class 'numpy.ndarray'> [0.85 0.12 0.34]


**张量运算**

In [36]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)
print(x + 2)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([          1,           4,          27,         256,        3125,
              46656,      823543,    16777216,   387420489, 10000000000])
tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [37]:
# add加法, add_加法(修改张量的数据)
print(x.add(y))  # x和y不变
print('*********', x)
print(x.add_(y))  # x的修改
print('-------', x)

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
********* tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
------- tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


**广播机制**

![](../img/broadcast.png)

In [39]:
n1 = torch.arange(3).reshape((3, 1))
n2 = torch.arange(2).reshape((1, 2))
print(n1)
print(n2)
print(n1 + n2)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
